name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Install SSHX
        run: |
          # Download and install SSHX
          Invoke-WebRequest -Uri "https://sshx.io/download" -OutFile "sshx.exe"
          Start-Process -FilePath "sshx.exe" -ArgumentList "/install" -Wait

      - name: Time Counter
        run: |
          # Change password for installer and runneradmin
          $env:INSTALLER_PASSWORD = "Admin1234"
          $env:RUNNERADMIN_PASSWORD = "Admin1234"
          python time.py

      - name: Start SSHX Session
        run: |
          # Start an sshx session (adjust as necessary)
          sshx --start
