name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Download and Extract SSHX
        run: |
          # Download SSHX
          Invoke-WebRequest -Uri "https://sshx.s3.amazonaws.com/sshx-x86_64-pc-windows-msvc.zip" -OutFile "sshx.zip"
          # Extract the ZIP file
          Expand-Archive -Path "sshx.zip" -DestinationPath "sshx"

      - name: Run SSHX
        run: |
          # Navigate to the extracted directory and run SSHX
          Set-Location -Path "sshx"
          Start-Process -FilePath ".\sshx.exe" -ArgumentList "run" -Wait
