name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Change Passwords for Users
        run: |
          # Change password for runneradmin
          if (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue) {
            $password = ConvertTo-SecureString "Admin1234" -AsPlainText -Force
            Set-LocalUser -Name "runneradmin" -Password $password
            Write-Host "Password for runneradmin changed successfully."
          } else {
            Write-Warning "User runneradmin does not exist."
          }
          # Change password for installer
          if (Get-LocalUser -Name "installer" -ErrorAction SilentlyContinue) {
            $password = ConvertTo-SecureString "Admin1234" -AsPlainText -Force
            Set-LocalUser -Name "installer" -Password $password
            Write-Host "Password for installer changed successfully."
          } else {
            Write-Warning "User installer does not exist."
          }


      - name: Time Counter
        run: python time.py
